apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
      - apps
      - com.qansoft
      - storage.k8s.io
      - networking.k8s.io
      - rbac.authorization.k8s.io
    resources:
      - '*'