apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-operator
  labels:
    app: my-operator
spec:
  selector:
    matchLabels:
      app: my-operator
  template:
    metadata:
      labels:
        app: my-operator
    spec:
      serviceAccountName: my-operator-account
      containers:
      - name: operator
        image: springboot-k8s-operator:0.0.1-SNAPSHOT
        imagePullPolicy: Never
