/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.qansoft.code.springbootoperator.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Specification defines the desired state of Custom resource
 */
@ApiModel(description = "Specification defines the desired state of Custom resource")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-05-26T13:41:13.469Z[Etc/UTC]")
public class V1MyCrdSpec {
  public static final String SERIALIZED_NAME_CONFIG_MAP_TEXT = "configMapText";
  @SerializedName(SERIALIZED_NAME_CONFIG_MAP_TEXT)
  private String configMapText;


  public V1MyCrdSpec configMapText(String configMapText) {
    
    this.configMapText = configMapText;
    return this;
  }

   /**
   * Dummy text to put in config map
   * @return configMapText
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Dummy text to put in config map")

  public String getConfigMapText() {
    return configMapText;
  }


  public void setConfigMapText(String configMapText) {
    this.configMapText = configMapText;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1MyCrdSpec v1MyCrdSpec = (V1MyCrdSpec) o;
    return Objects.equals(this.configMapText, v1MyCrdSpec.configMapText);
  }

  @Override
  public int hashCode() {
    return Objects.hash(configMapText);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1MyCrdSpec {\n");
    sb.append("    configMapText: ").append(toIndentedString(configMapText)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

